### ISSUE TITLE
GitHub actions are not running for PRs

### ISSUE THREAD

**Issue by smolkaj** [googleinterns/p4-symbolic#20]

**Comment by KinanBab** [comment]
will fix, they only run for things pushed to master for now

**Comment by smolkaj** [comment]
Thanks. Just adding it here so we don't forget about it.

**Comment by smolkaj** [comment]
Actually, we don't want to run them on all branches because non-master branches are allowed to brake, since they may be experimental, and you don't want to receive an email about it everytime that happens.

**Comment by KinanBab** [comment]
I am going to make it so it can run on PRs to any base, but not commits that have no PRs.

**Comment by smolkaj** [comment]
That's even better. We should do the same for our other projects.
