### ISSUE TITLE
Review weird Bazel issue with c++17

### ISSUE THREAD

**Issue by KinanBab** [googleinterns/p4-symbolic#31]
Using .bazelrc to provide cxxopt="-std=c++17" only partly works:

- Seems to work fine when doing things like `bazel build //p4_symbolic:main`
- Does not work when doing `bazel build //...`: the cxxopt is not passed to gcc, I have verified this using -s to display and log sub-commands.
- Does not work when doing `bazel test <trule or ...>`, the cxxopt is not passed to build targets.

Putting copt explicitly in the cc_binary and cc_library rules passes the option to gcc correctly always, but ends up failing to link, because dependencies (specifically absl::Status) ends up being compiled several times (c++17 for our code and c++11 from pdpi) causing duplicate definitions when linking.

Current work around: replace <unorder_map>.insert_or_assign with c++11 compatible code. c++17 syntax (e.g. structural binding) still works but gcc outputs a warning.

**Comment by smolkaj** [comment]
Can you just remove `ccxopt` entirely from `.bazelrc`? AFAIK this will make the compiler use the latest version of the C++ standard, which is what we want.

**Comment by KinanBab** [comment]
That did not work, I have confirmed by looking at the subcommands that it uses C++0x by default (strange).

**Comment by KinanBab** [comment]
using host_cxxopt in addition to cxxopt fixes hits. host_cxxopt applies the standard to test rules and build rules as dependencies to test rules.
