### ISSUE TITLE
File Structure reorganization

### ISSUE THREAD

**Issue by KinanBab** [googleinterns/p4-symbolic#7]
- put all first-phase parsing protobuf definitions in a single file
- put all source code (what is now main.cc) and tests and golden files under src/bmv2-parser
- put all SMT related code (including z3-samples) under src/smt
- rewrite veth setup bash script to be a lot simpler
- split up abstract/independent bazel rules into separate files

**Comment by stefanheule** [comment]
Could we also rename all BUILD files to BUILD.bazel and the same for WORKSPACE? That makes it more obvious what these are for non-bazel users.
