### ISSUE TITLE
Rename src to p4_symbolic

### ISSUE THREAD

**Issue by smolkaj** [googleinterns/p4-symbolic#9]
I know this may seems a bit awkward, but since we're using Bazel we should probably rename the `src` folder to `p4_symbolic`. The reason is that the C++ include path, for this project and projects depending on our project, is relative to the WORKSPACE file.
```C++
#include "src/foo.h"          // Current include path looks like this.
#include "p4_symbolic/foo.h"  // After renaming `src` to `p4_symbolic`.
```
@stefanheule

**Comment by stefanheule** [comment]
Yes, I agree. absl and other libraries do the same.

**Comment by KinanBab** [comment]
yeah I like this idea too

**Comment by KinanBab** [comment]
This is now implement in #8.
